export default [
    {
        img: "place_2.png",
        country: "Greece",
        city: "Athens",
        distance: "48 kilometers",
        rating: "5.0",
        date: "April 20 - 25",
        price: 136,
    },
    {
        img: "place_3.png",
        country: "Spain",
        city: "Barcelona",
        distance: "20 kilometers",
        rating: "4.8",
        date: "May 1 - 5",
        price: 180,
    },
    {
        img: "place_4.png",
        country: "Italy",
        city: "Rome",
        distance: "30 kilometers",
        rating: "4.7",
        date: "June 10 - 15",
        price: 220,
    },
    {
        img: "place_5.png",
        country: "France",
        city: "Paris",
        distance: "15 kilometers",
        rating: "4.9",
        date: "July 4 - 10",
        price: 250,
    },
    {
        img: "place_6.png",
        country: "Thailand",
        city: "Bangkok",
        distance: "10 kilometers",
        rating: "4.6",
        date: "August 15 - 20",
        price: 100,
    },
    {
        img: "place_7.png",
        country: "Japan",
        city: "Tokyo",
        distance: "5 kilometers",
        rating: "4.8",
        date: "September 10 - 15",
        price: 300,
    },
    {
        img: "place_8.png",
        country: "Australia",
        city: "Sydney",
        distance: "20 kilometers",
        rating: "4.7",
        date: "October 10 - 15",
        price: 280,
    },
    {
        img: "place_9.png",
        country: "USA",
        city: "New York",
        distance: "5 kilometers",
        rating: "4.9",
        date: "November 1 - 5",
        price: 350,
    },
    {
        img: "place_10.png",
        country: "Mexico",
        city: "Cancun",
        distance: "10 kilometers",
        rating: "4.6",
        date: "December 20 - 25",
        price: 180,
    },
    {
        img: "place_11.png",
        country: "Brazil",
        city: "Rio de Janeiro",
        distance: "25 kilometers",
        rating: "4.8",
        date: "January 5 - 10",
        price: 220,
    },
    {
        img: "place_12.png",
        country: "Canada",
        city: "Vancouver",
        distance: "10 kilometers",
        rating: "4.7",
        date: "February 10 - 15",
        price: 250,
    },
    {
        img: "place_13.png",
        country: "India",
        city: "New Delhi",
        distance: "5 kilometers",
        rating: "4.9",
        date: "March 15 - 20",
        price: 180,
    },
    {
        img: "place_14.png",
        country: "France",
        city: "Paris",
        distance: "3 kilometers",
        rating: "4.8",
        date: "July 10 - 15",
        price: 122
    },
    {
        img: "place_15.png",
        country: "France",
        city: "Nice",
        distance: "2 kilometers",
        rating: "4.4",
        date: "August 5 - 10",
        price: 110
    },
    {
        img: "place_16.png",
        country: "Italy",
        city: "Rome",
        distance: "7 kilometers",
        rating: "4.6",
        date: "September 15 - 20",
        price: 99
    },
    {
        img: "place_17.png",
        country: "Italy",
        city: "Florence",
        distance: "3 kilometers",
        rating: "4.3",
        date: "October 1 - 5",
        price: 85
    },
    {
        img: "place_18.png",
        country: "Japan",
        city: "Tokyo",
        distance: "12 kilometers",
        rating: "4.7",
        date: "November 15 - 20",
        price: 120
    },
    {
        img: "place_19.png",
        country: "Japan",
        city: "Osaka",
        distance: "8 kilometers",
        rating: "4.2",
        date: "December 1 - 5",
        price: 98
    },
    {
        img: "place_20.png",
        country: "Australia",
        city: "Sydney",
        distance: "5 kilometers",
        rating: "4.5",
        date: "January 10 - 15",
        price: 105
    },
    {
        img: "place_21.png",
        country: "Australia",
        city: "Melbourne",
        distance: "3 kilometers",
        rating: "4.4",
        date: "February 5 - 10",
        price: 99
    }
]
